FROM node:16-alpine

# install dependencies
WORKDIR /app
COPY package.json ./
RUN yarn

# Copy all local files into the image.
COPY . .

RUN yarn run build


FROM node:16-alpine

WORKDIR /app
COPY --from=0 /app .
RUN yarn global add pm2
COPY . .
ENV NODE_ENV=production
EXPOSE 3000
CMD ["pm2-runtime", "./build"]