version: "3.9"
services:
  backend:
    container_name: subme-backend
    build:
      context: backend
      dockerfile: Dockerfile.production
    depends_on:
      - db

  frontend:
    container_name: subme-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.production
    depends_on:
      - backend

  proxy:
    container_name: subme-proxy
    image: envoyproxy/envoy:v1.19.1
    ports:
      - 3000:3000
    volumes:
      - ./envoy-proxy-config.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - frontend

  db:
    container_name: subme-db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: SgcYnDP8KJk2i76JEKvWX9OJW1gOWuRtrk7HeJrZu74=
      POSTGRES_USER: subme
      POSTGRES_DB: subme
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: