version: "3.9"
services:
  backend:
    container_name: subme-backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_CONN: postgres://subme:SgcYnDP8KJk2i76JEKvWX9OJW1gOWuRtrk7HeJrZu74=@db:5432/subme
      SECRET: 5f6d4d80aca6791310ef0e322fc484c014504fb1399501e6cf6517013143da5c # openssl rand -hex 32
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080 #7 day
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - './backend:/code'
    depends_on:
      - db

  frontend:
    container_name: subme-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'

  proxy:
    container_name: subme-proxy
    image: envoyproxy/envoy:v1.19.1
    ports:
      - 3000:3000
    volumes:
      - ./envoy-proxy-config.yaml:/etc/envoy/envoy.yaml

  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2021-09-24T00-24-24Z
    command: server /data --console-address ":3001"
    expose:
      - 9000
      - 3001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:3000
    volumes:
      - minio-data:/data
    ports:
      - 3001:3001
      - 9000:9000

  db:
    container_name: subme-db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: SgcYnDP8KJk2i76JEKvWX9OJW1gOWuRtrk7HeJrZu74=
      POSTGRES_USER: subme
      POSTGRES_DB: subme
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  adminer:
    container_name: subme-db-admin
    image: adminer
    restart: always
    ports:
      - 3002:8080

volumes:
  db-data:
  minio-data: