version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/subme-backend'
    # depends_on:
    #   - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - './frontend:/app'

  envoy:
    image: envoyproxy/envoy:v1.19.1
    ports:
      - "3000:3000"
    volumes:
      - ./envoy-proxy-config.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - backend
      - frontend

  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: SgcYnDP8KJk2i76JEKvWX9OJW1gOWuRtrk7HeJrZu74=
  #     POSTGRES_USER: subme
  #     POSTGRES_DB: subme
  #   volumes:
  #     - 'db-data:/var/lib/postgresql/data'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 3001:8080
  #   depends_on:
  #     - db

volumes:
  db-data: