FROM rust:1.55 as builder
WORKDIR /usr/src/subme-backend
COPY . .
RUN rm -r .cargo/ && cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/subme-backend /usr/local/bin/subme-backend
EXPOSE 4000
CMD ["subme-backend"]