FROM tiangolo/uvicorn-gunicorn:python3.9-slim

COPY ./requirements.txt /app/requirements.txt

RUN apt update && apt-get install gcc -y && pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app/app

ENV BIND=0.0.0.0:4000
EXPOSE 4000